# Add project specific ProGuard rules here.
# You can control the set of applied configuration files using the
# proguardFiles setting in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

# Uncomment this to preserve the line number information for
# debugging stack traces.
#-keepattributes SourceFile,LineNumberTable

# If you keep the line number information, uncomment this to
# hide the original source file name.
#-renamesourcefileattribute SourceFile

# ─── Jackson Serialization ────────────────────────────────────────────────────
# Keep Jackson annotations
-keepattributes *Annotation*
-keepattributes Signature
-keepattributes Exceptions

# Keep Jackson classes
-keep class com.fasterxml.jackson.** { *; }
-keep class com.fasterxml.jackson.databind.** { *; }
-dontwarn com.fasterxml.jackson.databind.**

# Keep all DTO classes (generated by OpenAPI)
-keep class io.github.phunguy65.zms.data.remote.dto.** { *; }
-keepclassmembers class io.github.phunguy65.zms.data.remote.dto.** {
    <init>(...);
    <fields>;
    <methods>;
}

# Keep classes with @JsonCreator and @JsonProperty annotations
-keepclassmembers class * {
    @com.fasterxml.jackson.annotation.JsonCreator *;
    @com.fasterxml.jackson.annotation.JsonProperty *;
}

# ─── LiveKit / WebRTC ─────────────────────────────────────────────────────────
# LiveKit SDK consumer rules should handle most cases, but we add explicit rules
# for WebRTC and LiveKit core classes to ensure they are not stripped.

# Keep WebRTC native interfaces
-keep class org.webrtc.** { *; }
-dontwarn org.webrtc.**

# Keep LiveKit SDK classes
-keep class io.livekit.** { *; }
-keep class livekit.** { *; }
-dontwarn io.livekit.**
-dontwarn livekit.**

# Keep SurfaceViewRenderer for video rendering
-keep class org.webrtc.SurfaceViewRenderer { *; }
-keep class org.webrtc.TextureViewRenderer { *; }

# Keep VideoTrack and AudioTrack for media handling
-keep class org.webrtc.VideoTrack { *; }
-keep class org.webrtc.AudioTrack { *; }
-keep class org.webrtc.MediaStreamTrack { *; }
