package io.github.phunguy65.zms.meetingmanagement.domain;

import io.github.phunguy65.zms.shared.domain.ErrorCode;

/**
 * Machine-readable error codes for JSend {@code fail} responses.
 */
public enum MeetingErrorCode implements ErrorCode {
    MEETING_NOT_FOUND,
    INVALID_STATUS_TRANSITION,
    INVALID_RECORDING_TRANSITION,
    RECORDING_ALREADY_ACTIVE,
    NO_ACTIVE_RECORDING,
    RECORDING_NOT_FOUND,
    SHORT_CODE_EXHAUSTED,
    NOT_AUTHORIZED,
    NOT_OWNER,
    NOT_PARTICIPANT,
    PARTICIPATION_LOG_NOT_FOUND,
    GUEST_NOT_ALLOWED,
    LIVEKIT_UNAVAILABLE,
    MEETING_FULL,
    INVITEE_NOT_FOUND,
    INVALID_MEETING_DURATION,
    USER_SERVICE_UNAVAILABLE,
    INVALID_SETTINGS,
    INVALID_INVITEE_TRANSITION,
    INVALID_PASSWORD,
    JOIN_REQUEST_NOT_FOUND,
    JOIN_REQUEST_EXPIRED,
    INVALID_JOIN_REQUEST_TRANSITION,
    NOT_WAITING_FOR_APPROVAL,
    CAN_NOT_KICK_SELF,
    USER_NOT_IN_MEETING,
    INVALID_KICK_TARGET,
    PARTIAL_APPROVAL_FAILURE
}
