CREATE TABLE outbox_event
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id   UUID         NOT NULL,
    aggregate_type VARCHAR(100) NOT NULL,
    event_type     VARCHAR(255) NOT NULL,
    topic          VARCHAR(255) NOT NULL,
    payload        CLOB         NOT NULL,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at   TIMESTAMP,
    retry_count    INT          NOT NULL DEFAULT 0,
    last_error     CLOB
);

CREATE INDEX idx_outbox_event_unpublished ON outbox_event (created_at);
